config/routes.rb
Rails.application.routes.draw do



  get 'home/home'
  root 'notes#index'
  post 'notes/new'
  get 'users/profile'
  resources :users
  resources :notes do
    member do
      patch "upvote", to: "notes#upvote"
      patch "downvote", to: "notes#downvote"
    resources :tasks

    end
  end

  namespace :notes do
    resources :tasks
  end

  devise_for :users

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  acts_as_votable cacheable_strategy: :update_columns

  has_many :votes

  def enbedable_url
    youtube_id = description.split("?v=").last
    "https://www.youtube.com/embed/#{youtube_id}"
  end

end
@note = Note.new(:name => '')
@note.save

@note.liked_by @user
@note.votes_for.size # => 1

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  # GET /notes or /notes.json
  def index
    @notes = current_user.notes.order(cached_votes_score: :desc)
    if nil
    end
  end

  def upvote
      @note = current_user.notes.find(params[:id])
      if current_user.voted_up_on? @note
        @note.unvote_by current_user
      else
        @note.upvote_by current_user
      end
      render "vote.js.erb"
  end
  def downvote
      @note = current_user.notes.find(params[:id])
      if current_user.voted_down_on? @note
        @note.unvote_by current_user
      else
        @note.downvote_by current_user
      end
      render "vote.js.erb"
  end
  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:name, :description)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_downvote_link.html.erb
<%= content_tag "div", id: "downvote-#{note.id}" do %>
 <%= link_to downvote_note_path(note), method: :patch, remote: true do %>
 <% if current_user.voted_down_on? note %>
    unvote
  <% else %>
     downvote!
 <% end %>
<% end %>
<% end %>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<main>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :"Put youtube URL here > " %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit :"Create Video Link Now "%>
  </div>
</main>
<% end %>

app/views/notes/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{note.id}" do %>
 <%= link_to upvote_note_path(note), method: :patch, remote: true do %>
 <% if current_user.voted_up_on? note %>
    unvote
  <% else %>
     vote!
 <% end %>
<% end %>
<% end %>

app/views/notes/_votes_score.html.erb
<%= content_tag "div", id: "votes-score-#{note.id}" do %>
  <%= note.cached_votes_score %>
<% end %>

app/views/notes/edit.html.erb
<div class="h1">
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>
</div>

app/views/notes/index.html.erb
<!DOCTYPE html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">


<h2 class="bluehand">listen to chilledcow</h2>

<div class="content2">
<iframe height="320px" width="100%" src="https://www.youtube.com/embed/DWcJFNfaw9c?autoplay=1"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"> </iframe>
</div>

      <p class="greyhand">YOUTUBE LIKE A FOREST</p>
      <th colspan="3"></th>

    <% @notes.each do |note| %>

        <!--<td><%= note.name %></td> -->
    <div class="bluehand">
      <p style="text-align: center;"><iframe  height="" width="" src="<%= note.enbedable_url %>" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"> </iframe></p>

     <tr class="bluehand">
      <td><button class="fa fa-thumbs-up"><%= render "notes/upvote_link", note: note %></button></td>
      <td><button class="fa fa-thumbs-down"><%= render "notes/downvote_link", note: note %></button></td>
      <td><%= render "notes/votes_score", note: note %></td>
      <td><button><%= link_to 'Show', note %></button></td>
      <td><button><%= link_to 'Edit', edit_note_path(note) %></button></td>
      <td><button><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      <td><button><%= link_to 'Add', new_note_path %></button></td>
      <br> </br>
      </tr>
    </div>
    <% end %>

<div class="lineupdamnit">
    <footer class="">

      Copyright 42069 all rights reserved

         
    </footer>
  </div>

app/views/notes/new.html.erb
<div class="h1">
<h1>New Video</h1>


<%= render 'form', note: @note  %>

<%= link_to 'Back', notes_path %>
</div>

app/views/notes/show.html.erb
<div class="content2">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @note.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>
<iframe autoplay height="500px" width="100%" src="<%= @note.enbedable_url %>" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"> </iframe>

<p>
  <strong>User:</strong>
  <%= @note.user_id %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>
</div>


<%# show.html.erb -> /notes/1 %>

app/views/notes/vote.js.erb
document.getElementById("upvote-<%= @note.id %>").innerHTML = "<%= j render "notes/upvote_link", note: @note %>";
document.getElementById("downvote-<%= @note.id %>").innerHTML = "<%= j render "notes/downvote_link", note: @note %>";
document.getElementById("votes-score-<%= @note.id %>").innerHTML = "<%= j render "notes/votes_score", note: @note %>";