config/routes.rb
Rails.application.routes.draw do



  get 'home/home'
  root 'notes#index'
  post 'notes/new'
  get 'users/profile'
  resources :users
  resources :notes do
    member do
      patch "upvote", to: "notes#upvote"
      patch "downvote", to: "notes#downvote"
    resources :tasks

    end
  end

  namespace :notes do
    resources :tasks
  end

  devise_for :users

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :notes
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notes
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET notes/1/tasks
  def index
    @tasks = @notes.tasks
  end

  # GET notes/1/tasks/1
  def show
  end

  # GET notes/1/tasks/new
  def new
    @task = @notes.tasks.build
  end

  # GET notes/1/tasks/1/edit
  def edit
  end

  # POST notes/1/tasks
  def create
    @task = @notes.tasks.build(task_params)

    if @task.save
      redirect_to([@task.notes, @task], notice: 'Task was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT notes/1/tasks/1
  def update
    if @task.update_attributes(task_params)
      redirect_to([@task.notes, @task], notice: 'Task was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE notes/1/tasks/1
  def destroy
    @task.destroy

    redirect_to notes_tasks_url(@notes)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notes
      @notes = current_user.notes.find(params[:notes_id])
    end

    def set_task
      @task = @notes.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :notes_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper


end

app/views/tasks/_form.html.erb
<%= form_with(model: [@task.notes, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', [@task.notes, @task] %> |
<%= link_to 'Back', notes_tasks_path(@task.notes) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.notes %></td>
    <td><%= link_to 'Show', [task.notes, task] %></td>
    <td><%= link_to 'Edit', edit_notes_task_path(task.notes, task) %></td>
    <td><%= link_to 'Destroy', [task.notes, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_notes_task_path(params[:notes_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_tasks_path(@task.notes) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Notes:</b>
  <%= @task.notes %>
</p>


<%= link_to 'Edit', edit_notes_task_path(@task.notes, @task) %> |
<%= link_to 'Back', notes_tasks_path(@task.notes) %>